  uses: ncruces/go-coverage-report@v0
  with:
    report: 'true'
    chart: 'true'
    amend: 'false'
  if: |
    matrix.os == 'ubuntu-latest' &&
    github.event_name == 'push'  
  continue-on-error: true
